# Generated by Django 5.0.6 on 2025-03-30 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('CardID', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('GreenDescription', models.CharField(default='', max_length=200)),
                ('AmberDescription', models.CharField(default='', max_length=200)),
                ('RedDescription', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('sessionID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('sessionName', models.CharField(default='New Session', max_length=200)),
                ('sessionStartData', models.DateTimeField(auto_now_add=True)),
                ('sessionEndData', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('departmentID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('departmentName', models.CharField(max_length=200, null=True)),
                ('departmentCards', models.ManyToManyField(to='Company.card')),
            ],
        ),
        migrations.CreateModel(
            name='SessionCard',
            fields=[
                ('CardID', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('GreenDescription', models.CharField(default='', max_length=200)),
                ('AmberDescription', models.CharField(default='', max_length=200)),
                ('RedDescription', models.CharField(default='', max_length=200)),
                ('GreenVote', models.IntegerField(default=0)),
                ('AmberVote', models.IntegerField(default=0)),
                ('RedVote', models.IntegerField(default=0)),
                ('SessionID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Company.session')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('teamID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('teamName', models.CharField(default='', max_length=200)),
                ('departmentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Company.department')),
            ],
        ),
        migrations.AddField(
            model_name='session',
            name='teamID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Company.team'),
        ),
    ]
