# Generated by Django 5.0.6 on 2025-03-30 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='departmentCards',
        ),
        migrations.RemoveField(
            model_name='sessioncard',
            name='SessionID',
        ),
        migrations.DeleteModel(
            name='Card',
        ),
        migrations.DeleteModel(
            name='SessionCard',
        ),
    ]
