# Generated by Django 5.0.6 on 2025-03-30 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0003_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='departmentID',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Company.department'),
        ),
    ]
