# Generated by Django 5.2 on 2025-04-07 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0005_account_userid_alter_session_sessionstartdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('cardID', models.AutoField(primary_key=True, serialize=False)),
                ('greenDescription', models.TextField(max_length=500)),
                ('amberDescription', models.TextField(max_length=500)),
                ('redDescription', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='SessionCard',
            fields=[
                ('sessionCardID', models.AutoField(primary_key=True, serialize=False)),
                ('greenVote', models.IntegerField(default=0)),
                ('amberVote', models.IntegerField(default=0)),
                ('redVote', models.IntegerField(default=0)),
                ('greenDescription', models.CharField(default='', max_length=500)),
                ('amberDescription', models.CharField(default='', max_length=500)),
                ('redDescription', models.CharField(default='', max_length=500)),
                ('sessionID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Company.session')),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('voteCode', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('greenVote', models.BooleanField(default=False)),
                ('amberVote', models.BooleanField(default=False)),
                ('redVote', models.BooleanField(default=False)),
                ('comment', models.CharField(max_length=500)),
                ('accountCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Company.account')),
                ('sessionCardID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Company.sessioncard')),
            ],
        ),
        migrations.CreateModel(
            name='CardToDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Company.card')),
                ('departmentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Company.department')),
            ],
            options={
                'unique_together': {('cardID', 'departmentID')},
            },
        ),
    ]
