# Generated by Django 5.1.7 on 2025-04-20 08:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('cardID', models.AutoField(primary_key=True, serialize=False)),
                ('greenDescription', models.TextField(max_length=500)),
                ('amberDescription', models.TextField(max_length=500)),
                ('redDescription', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('departmentID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('departmentName', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('sessionID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('sessionName', models.CharField(default='New Session', max_length=200)),
                ('sessionStartData', models.DateTimeField()),
                ('sessionEndData', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('accountCode', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(default='', max_length=200)),
                ('userName', models.CharField(default='', max_length=200)),
                ('emailAddress', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=254)),
                ('accountRole', models.CharField(choices=[('ENGINEER', 'ENGINEER'), ('TEAM LEADER', 'TEAM LEADER'), ('DEPARTMENT LEADER', 'DEPARTMENT LEADER'), ('SENIOR MANAGER', 'SENIOR MANAGER')], default='ENGINEER', max_length=20)),
                ('userID', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('departmentID', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='forgotpassword.department')),
            ],
        ),
        migrations.CreateModel(
            name='SessionCard',
            fields=[
                ('sessionCardID', models.AutoField(primary_key=True, serialize=False)),
                ('greenVote', models.IntegerField(default=0)),
                ('amberVote', models.IntegerField(default=0)),
                ('redVote', models.IntegerField(default=0)),
                ('greenDescription', models.CharField(default='', max_length=500)),
                ('amberDescription', models.CharField(default='', max_length=500)),
                ('redDescription', models.CharField(default='', max_length=500)),
                ('sessionID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forgotpassword.session')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('teamID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('teamName', models.CharField(default='', max_length=200)),
                ('departmentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forgotpassword.department')),
            ],
        ),
        migrations.AddField(
            model_name='session',
            name='teamID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forgotpassword.team'),
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('voteCode', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('greenVote', models.BooleanField(default=False)),
                ('amberVote', models.BooleanField(default=False)),
                ('redVote', models.BooleanField(default=False)),
                ('comment', models.CharField(max_length=500)),
                ('accountCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forgotpassword.account')),
                ('sessionCardID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forgotpassword.sessioncard')),
            ],
        ),
        migrations.CreateModel(
            name='CardToDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forgotpassword.card')),
                ('departmentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forgotpassword.department')),
            ],
            options={
                'unique_together': {('cardID', 'departmentID')},
            },
        ),
    ]
