# Generated by Django 5.1.7 on 2025-04-20 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forgotpassword', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='password',
        ),
        migrations.AlterField(
            model_name='account',
            name='departmentID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='forgotpassword.department'),
        ),
        migrations.AlterField(
            model_name='account',
            name='emailAddress',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='userName',
            field=models.CharField(default='', max_length=200, unique=True),
        ),
    ]
