# Generated by Django 5.1.7 on 2025-04-20 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forgotpassword', '0002_remove_account_password_alter_account_departmentid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
