# Generated by Django 5.2 on 2025-04-24 12:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forgotpassword', '0003_account_password'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='userID',
            new_name='accountID',
        ),
        migrations.RemoveField(
            model_name='account',
            name='accountCode',
        ),
        migrations.RemoveField(
            model_name='account',
            name='accountRole',
        ),
        migrations.RemoveField(
            model_name='account',
            name='emailAddress',
        ),
        migrations.RemoveField(
            model_name='account',
            name='name',
        ),
        migrations.RemoveField(
            model_name='account',
            name='password',
        ),
        migrations.RemoveField(
            model_name='account',
            name='userName',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='accountCode',
        ),
        migrations.AddField(
            model_name='account',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='department',
            name='departmentCards',
            field=models.ManyToManyField(to='forgotpassword.card'),
        ),
        migrations.AddField(
            model_name='vote',
            name='userID',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='account',
            name='departmentID',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='forgotpassword.department'),
        ),
        migrations.AlterField(
            model_name='card',
            name='amberDescription',
            field=models.TextField(max_length=150),
        ),
        migrations.AlterField(
            model_name='card',
            name='cardID',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='greenDescription',
            field=models.TextField(max_length=150),
        ),
        migrations.AlterField(
            model_name='card',
            name='redDescription',
            field=models.TextField(max_length=150),
        ),
        migrations.AlterField(
            model_name='sessioncard',
            name='sessionCardID',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='vote',
            name='amberVote',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='vote',
            name='comment',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='vote',
            name='greenVote',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='vote',
            name='redVote',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='CardToDepartment',
        ),
    ]
