# Generated by Django 5.0.6 on 2025-04-10 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0008_card_cardtodepartment_sessioncard_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='departmentCards',
            field=models.ManyToManyField(to='Company.card'),
        ),
        migrations.DeleteModel(
            name='CardToDepartment',
        ),
    ]
