# Generated by Django 5.1.5 on 2025-04-26 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0010_alter_account_departmentid'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='cardImage',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='sessioncard',
            name='cardImage',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='sessioncard',
            name='amberDescription',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='sessioncard',
            name='greenDescription',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='sessioncard',
            name='redDescription',
            field=models.CharField(default='', max_length=150),
        ),
    ]
