# Generated by Django 5.1.5 on 2025-04-30 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0013_alter_card_cardimage_alter_sessioncard_cardimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='cardImage',
        ),
        migrations.RemoveField(
            model_name='sessioncard',
            name='cardImage',
        ),
    ]
