# Generated by Django 5.0.6 on 2025-04-07 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0005_account_userid_alter_session_sessionstartdata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
