# Generated by Django 5.0.6 on 2025-04-10 15:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0007_account'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('cardID', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('greenDescription', models.TextField(max_length=150)),
                ('amberDescription', models.TextField(max_length=150)),
                ('redDescription', models.TextField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='CardToDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Company.card')),
                ('departmentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Company.department')),
            ],
        ),
        migrations.CreateModel(
            name='SessionCard',
            fields=[
                ('sessionCardID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('greenVote', models.IntegerField(default=0)),
                ('amberVote', models.IntegerField(default=0)),
                ('redVote', models.IntegerField(default=0)),
                ('greenDescription', models.CharField(default='', max_length=500)),
                ('amberDescription', models.CharField(default='', max_length=500)),
                ('redDescription', models.CharField(default='', max_length=500)),
                ('sessionID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Company.session')),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('voteCode', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('greenVote', models.IntegerField(default=0)),
                ('amberVote', models.IntegerField(default=0)),
                ('redVote', models.IntegerField(default=0)),
                ('comment', models.CharField(max_length=200)),
                ('sessionCardID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Company.sessioncard')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
