# Generated by Django 5.0.6 on 2025-04-23 23:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0009_department_departmentcards_delete_cardtodepartment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='departmentID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Company.department'),
        ),
    ]
