# Generated by Django 5.1.5 on 2025-04-27 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0011_card_cardimage_sessioncard_cardimage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='cardImage',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='sessioncard',
            name='cardImage',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
