# Generated by Django 5.1.5 on 2025-04-27 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0012_alter_card_cardimage_alter_sessioncard_cardimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='cardImage',
            field=models.ImageField(null=True, upload_to='cards/'),
        ),
        migrations.AlterField(
            model_name='sessioncard',
            name='cardImage',
            field=models.ImageField(null=True, upload_to='cards/'),
        ),
    ]
